# Generated by Django 6.0.6 on 2026-06-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bread_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_bg',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instr_av',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instr_initials',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='tag_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
