# Generated by Django 6.0.6 on 2026-06-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.course'),
        ),
    ]
